### ISSUE TITLE
Add ARM build

### ISSUE THREAD

**Issue by 2phost** [microcks/microcks-ansible-operator#10]
**Describe the bug**

When I run this container on an ARM system I see the following error:
standard_init_linux.go:207: exec user process caused "exec format error"

I think it may be related to the system being ARM based, and your image was not compiled in ARM based systems.
Is it possible to add an ARM build? For example using the tag arm and arm64 for each system.

Tested on Kubernetes 1.17

**Comment by lbroudoux** [comment]
Now done on the new `quay.io/microcks/microcks-ansible-operator:nightly` image. Soon to be released in `1.7.0!
