### ISSUE TITLE
Support auto-scaling for the main microcks Deployment

### ISSUE THREAD

**Issue by robvalk** [microcks/microcks-ansible-operator#109]
### Reason/Context

Microcks's high performance makes it deal for both functional and performance testing. However fixed scaling for the core `microcks`  Deployment makes it hard to scale the microcks layer up and down for performance testing.

### Description

Supporting auto-scaling of the microcks Deployment , via standard k8s auto-scaling constructs.

### Implementation ideas

Include a `HorizontalPodAutoscaler` in the k8s resources managed from the `Microcks` CR. 
Or make the `Microcks` CR implement the `scale` [sub-resource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource), allowing e.g. HPA or KEDA to control auto-scaling.

**Comment by yada** [comment]
Hi @robvalk,

I'm sorry for the long delay in our answer on this issue. 

This topic is essential for Microcks adopters running it at scale and with advanced GitOps expertise and practices.
So, we are working on a new operator to manage all Microcks configurations using customer resources for advanced community users. 

Please see and join us on this new repo: https://github.com/microcks/microcks-operator

Looking forward to your ideas/comments/validation on this new operator (WIP).

Regards,
Yacine
