### ISSUE TITLE
Operator install in one single file

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks-ansible-operator#22]
Create a single file install for all the resources required by the operator. For example, like strimzi does.

**Comment by lbroudoux** [comment]
HI @hguerrero,

Done ;-)

I can not found any documentation on the Strimzi simple installation procedure though ... The instructions found [here](https://strimzi.io/docs/operators/latest/deploying.html#cluster-operator-str) always imply cloning the repository, sedding some files and applying a whole folder full of YAML files.

Have you seen something simpler than that ?

Don't know if you seen them but we have simple `install-latest-on-minikube.sh` and `install-latest-on-openshift.sh` scripts that are pretty simple to use if you want to quickly drive a test?

**Comment by hguerrero** [comment]
Hi @lbroudoux 

this is the suggested approach: https://strimzi.io/quickstarts/

```Applying Strimzi installation file

Next we apply the Strimzi install files, including ClusterRoles, ClusterRoleBindings and some Custom Resource Definitions (CRDs). The CRDs define the schemas used for declarative management of the Kafka cluster, Kafka topics and users.

kubectl apply -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka
```

**Comment by lbroudoux** [comment]
Ha ha ! Ok, understood !

However they should have dynamic behavior on the server side to render correct YAML files including the `namespace` param. No ? As we just have a website holding static content, it will be tricky... Other ideas ?

**Comment by lbroudoux** [comment]
Or it could be a big one-liner command doing `curl | sed | kubectl apply -n -` sort of things ?

**Comment by hguerrero** [comment]
It depends how many namespaces dependencies are in the resources. I think everything should land in the microcks namespace right? is the operator clusterwide or namespaced?

**Comment by lbroudoux** [comment]
The operator is namespaced

**Comment by hguerrero** [comment]
The yes, a `curl | sed | kubectl` should work fine.

**Comment by lbroudoux** [comment]
Not really a "one command line install" but here's the shorter you can make:

```sh
minikube start --vm=true --cpus=4 --memory=6144 # 2cpus and 2GB default memory isn't always enough
kubectl create namespace microcks
kubectl apply -f 'https://strimzi.io/install/latest?namespace=microcks' -n microcks
kubectl apply -f https://microcks.io/operator/operator-latest.yaml -n microcks
curl https://microcks.io/operator/minikube-features.yaml -s | sed 's/KUBE_APPS_URL/'$(minikube ip)'.nip.io/g' | kubectl apply -n microcks -f -
```

For those who'd need to access cluster for outside, they'll also have to add:

```sh
minikube addons enable ingress
kubectl patch -n kube-system deployment/ingress-nginx-controller --type='json' \
    -p '[{"op":"add","path":"/spec/template/spec/containers/0/args/-","value":"--enable-ssl-passthrough"}]'
```

Full documentation should be added on Microcks.io though
