### ISSUE TITLE
Add default user for microcks

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks-ansible-operator#23]
Currently you only get the keycloak master realm user as  part of the operator install. It could be useful if we can also add a microcks user from the beginning to avoid new users the need to deep dive on keycloack to get started with microcks.

**Comment by lbroudoux** [comment]
Changes have been pushed into `quay.io/microcks/microcks-ansible-operator:latest` if one want to test it before `1.2.0` release.

**Comment by lbroudoux** [comment]
3 users have been added, 1 corresponding to each role/persona we have in Microcks:
* `user` with password `microcks123`,
* `manager` with password `microcks123`,
* `admin` with password `microcks123`
