### ISSUE TITLE
Allow to configure different images

### ISSUE THREAD

**Issue by ruromero** [microcks/microcks-ansible-operator#49]
I would like to use different image registries or internal ones for deploying Microcks. I think the `image` tag could be added to the CRD to allow that.

```
  mongodb:
    image: myregistry:5000/microcks/mongodb-34-centos7:latest
    install: true
```

**Comment by lbroudoux** [comment]
Hey Ruben, thanks for the suggestion. It should be doable for the 1.4.0 release.

**Comment by lbroudoux** [comment]
Hey @ruromero ! It is now available in `quay.io/microcks/microcks-ansible-operator:latest` operator image.

**Comment by ruromero** [comment]
Now I don't need it anymore...
I'm kidding, thanks a lot for taking care of this. I've become a Microcks fan!

Thanks @lbroudoux
