### ISSUE TITLE
MicrocksInstall is failing in 1.4.1

### ISSUE THREAD

**Issue by jonmwalton** [microcks/microcks-ansible-operator#55]
Since v1.4.1 the operator now fails to install a vanilla MicrocksInstall CRD. Most of the components get deployed except for the actual console. The error can be seen in the attached log.
[microcks-ansible-operator-68f54b6bcd-d6vhx-microcks-ansible-operator.log](https://github.com/microcks/microcks-ansible-operator/files/7304767/microcks-ansible-operator-68f54b6bcd-d6vhx-microcks-ansible-operator.log)

**Comment by lbroudoux** [comment]
This is probablye due to Jinja escaping charaters (`{% +%}`) that are not supported in current Operator SDK Ansible version...

**Comment by lbroudoux** [comment]
Hey ! I've produced a new `quay.io/microcks/microcks-ansible-operator:1.4.1` container image version. Could you check on your side?

**Comment by lbroudoux** [comment]
Yes the image has been patched. You should just ensure to kill your operator pod to force re-pulling the image.
