### ISSUE TITLE
[FEATURE] - Add the default credentials for microcks as secrets

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks-ansible-operator#71]
If the operator is creating a default user, it can generate a secret with the information for easy handle of that in the namespace.

**Comment by lbroudoux** [comment]
Hey @hguerrero! Not sure to understand the user you're talking about. Is it a Keycloak realm user (`admin`) or the `microcks-service-account` that is later used by deployed components?

**Comment by hguerrero** [comment]
I was referring to the _admin_ user from keycloak.
