### ISSUE TITLE
Wrong api version for kafka strimzi

### ISSUE THREAD

**Issue by mhkarimi1383** [microcks/microcks-ansible-operator#91]
We have `kafka.strimzi.io/v1beta2` is our cluster but this operator is using `kafka.strimzi.io/v1beta1` witch is wrong

I want to know if I can change that by envs or it should be fixed?

**Comment by mhkarimi1383** [comment]
I'm getting 
```
Failed to find exact match for kafka.strimzi.io/v1beta1.Kafka by [kind, name, singularName, shortNames]
```
while `use_strimzi_beta1` set to `false`

**Comment by lbroudoux** [comment]
Hi!

`useStrimziBeta1` value is `false` by default. So you don't have to set it explicitly. 
Kafka resource in `kafka.strimzi.io/v1beta2` is created as soon as you have:
* `features.async.enabled` == `true`
*  `features.async.kafka.install` == `true` (default value)
*  `('route.openshift.io' in api_groups or 'url' in features.async.kafka)` (depends on OpenShift or Kubernetes target)
*  `features.async.kafka.use_strimzi_beta1` == `false` (default value)

Can you check your `MicrocksInstall` CR values?

**Comment by mhkarimi1383** [comment]
Fixed by changing docker image tag of the operator,

please update examples
